version: "3.8"
services:

 # webapp:
 #   build: ./
 #   ports:
 #    - "8080:8080"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: Data
    volumes:
      - ./scripts/tables.sql:/docker-entrypoint-initdb.d/001_tables.sql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8000
